//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominationForm
    {
        public int Id { get; set; }
        public string Nominator { get; set; }
        public string email { get; set; }
        public string schoolDistrict { get; set; }
        public string position { get; set; }
        public string relationship { get; set; }
        public string nominee { get; set; }
        public int age { get; set; }
        public string contactInfo { get; set; }
        public string graduationDate { get; set; }
        public Nullable<bool> accepted { get; set; }
    }
}
