//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentApplication
    {
        public int Id { get; set; }
        public System.DateTime timestamp { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string currentSchool { get; set; }
        public Nullable<bool> eligible { get; set; }
        public int age { get; set; }
        public string phoneNumber { get; set; }
        public string graduationDate { get; set; }
    }
}
